spring:
  redis:
    database: 0       #Redis数据库索引（默认为0）
    host: 127.0.0.1        #Redis服务器地址
    port: 6379        #Redis服务器连接端口
    password:          #Redis服务器连接密码（默认为空）
    timeout: 5000      #连接超时时间（毫秒）
    pool:
      max-active: 600   #连接池最大连接数（使用负值表示没有限制）
      max-wait: 10000    #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 300     #连接池中的最大空闲连接
      min-idle: 10     #连接池中的最小空闲连接
  http:
    multipart:
      enabled: true
      max-file-size: 100MB       #(这里是限制的文件大小)
      max-request-size: 100MB    #(这里是限制的文件大小)
