server:
    port: 9009
spring:
  redis:
    database: 0       #Redis数据库索引（默认为0）
    host: 192.168.0.145        #Redis服务器地址
    port: 6379        #Redis服务器连接端口
    password:          #Redis服务器连接密码（默认为空）
    timeout: 5000      #连接超时时间（毫秒）
    pool:
      max-active: 600   #连接池最大连接数（使用负值表示没有限制）
      max-wait: 10000    #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 300     #连接池中的最大空闲连接
      min-idle: 10     #连接池中的最小空闲连接
  devtools:
    restart:
      enabled: true
  http:
    multipart:
      maxFileSize: 5Mb
      maxRequestSize: 5Mb
  cache:
    type: guava
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      cache: false
      content-type: text/html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.17:3306/yxb?characterEncoding=UTF-8&useSSL=true
    username: root
    password: root@yxb
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 5
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.yxbkj.yxb.domain.model
  typeEnumsPackage: com.yxbkj.yxb.domain.enums
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazyLoadingEnabled: true
    multipleResultSetsEnabled: true
    useColumnLabel: true
    defaultExecutorType: reuse
    defaultStatementTimeout: 25000
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true
    cacheEnabled: true
logging:
  level: info


file:
    upload:
        ftp:
           ip: 192.168.0.17
           port: 21
           username: yixiaobao
           password: yixiaobao@yxb
           serverPath: /
           httpPath: http://192.168.6.82/home/yixiaobao/
           localPath: D://data//file
    download:
        excelsize: 3000
user:
  files:
    base : files
    basePath : files